/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Team, SimulatorParams } from './types';

export const TEAMS_INITIAL: Team[] = [
  // --- GRUPO A ---
  {
    id: 'MEX',
    name: 'México',
    group: 'A',
    confederation: 'CONCACAF',
    fifaRanking: 15,
    elo: 1780,
    recentForm: 'WLDWD',
    recentGF: 1.5,
    recentGC: 1.2,
    offenseRating: 75,
    defenseRating: 72,
    formRating: 65,
    overallPower: 74,
  },
  {
    id: 'CMR',
    name: 'Camerún',
    group: 'A',
    confederation: 'CAF',
    fifaRanking: 51,
    elo: 1610,
    recentForm: 'LDWLD',
    recentGF: 1.1,
    recentGC: 1.5,
    offenseRating: 64,
    defenseRating: 58,
    formRating: 50,
    overallPower: 58,
  },
  {
    id: 'SWE',
    name: 'Suecia',
    group: 'A',
    confederation: 'UEFA',
    fifaRanking: 26,
    elo: 1770,
    recentForm: 'WLWWL',
    recentGF: 1.6,
    recentGC: 1.1,
    offenseRating: 76,
    defenseRating: 74,
    formRating: 70,
    overallPower: 75,
  },
  {
    id: 'NZL',
    name: 'Nueva Zelanda',
    group: 'A',
    confederation: 'OFC',
    fifaRanking: 104,
    elo: 1450,
    recentForm: 'WLDLL',
    recentGF: 0.9,
    recentGC: 1.8,
    offenseRating: 52,
    defenseRating: 48,
    formRating: 45,
    overallPower: 48,
  },

  // --- GRUPO B ---
  {
    id: 'ENG',
    name: 'Inglaterra',
    group: 'B',
    confederation: 'UEFA',
    fifaRanking: 4,
    elo: 2010,
    recentForm: 'WWLWW',
    recentGF: 2.3,
    recentGC: 0.7,
    offenseRating: 92,
    defenseRating: 88,
    formRating: 85,
    overallPower: 92,
  },
  {
    id: 'ECU',
    name: 'Ecuador',
    group: 'B',
    confederation: 'CONMEBOL',
    fifaRanking: 30,
    elo: 1840,
    recentForm: 'WWDLD',
    recentGF: 1.4,
    recentGC: 0.9,
    offenseRating: 74,
    defenseRating: 80,
    formRating: 72,
    overallPower: 78,
  },
  {
    id: 'KOR',
    name: 'Corea del Sur',
    group: 'B',
    confederation: 'AFC',
    fifaRanking: 22,
    elo: 1795,
    recentForm: 'DWDWW',
    recentGF: 1.8,
    recentGC: 1.2,
    offenseRating: 78,
    defenseRating: 72,
    formRating: 75,
    overallPower: 76,
  },
  {
    id: 'JAM',
    name: 'Jamaica',
    group: 'B',
    confederation: 'CONCACAF',
    fifaRanking: 53,
    elo: 1590,
    recentForm: 'LWLDD',
    recentGF: 1.0,
    recentGC: 1.4,
    offenseRating: 62,
    defenseRating: 60,
    formRating: 52,
    overallPower: 58,
  },

  // --- GRUPO C ---
  {
    id: 'ARG',
    name: 'Argentina',
    group: 'C',
    confederation: 'CONMEBOL',
    fifaRanking: 1,
    elo: 2130,
    recentForm: 'WWWWD',
    recentGF: 2.5,
    recentGC: 0.5,
    offenseRating: 95,
    defenseRating: 93,
    formRating: 95,
    overallPower: 96,
  },
  {
    id: 'POL',
    name: 'Polonia',
    group: 'C',
    confederation: 'UEFA',
    fifaRanking: 28,
    elo: 1730,
    recentForm: 'LDWLW',
    recentGF: 1.3,
    recentGC: 1.4,
    offenseRating: 72,
    defenseRating: 68,
    formRating: 58,
    overallPower: 69,
  },
  {
    id: 'EGY',
    name: 'Egipto',
    group: 'C',
    confederation: 'CAF',
    fifaRanking: 36,
    elo: 1700,
    recentForm: 'WDWLD',
    recentGF: 1.5,
    recentGC: 1.1,
    offenseRating: 73,
    defenseRating: 70,
    formRating: 65,
    overallPower: 70,
  },
  {
    id: 'KSA',
    name: 'Arabia Saudita',
    group: 'C',
    confederation: 'AFC',
    fifaRanking: 56,
    elo: 1580,
    recentForm: 'LDLLD',
    recentGF: 0.8,
    recentGC: 1.6,
    offenseRating: 58,
    defenseRating: 56,
    formRating: 44,
    overallPower: 53,
  },

  // --- GRUPO D ---
  {
    id: 'FRA',
    name: 'Francia',
    group: 'D',
    confederation: 'UEFA',
    fifaRanking: 2,
    elo: 2090,
    recentForm: 'WWWLD',
    recentGF: 2.4,
    recentGC: 0.8,
    offenseRating: 96,
    defenseRating: 89,
    formRating: 88,
    overallPower: 94,
  },
  {
    id: 'CHI',
    name: 'Chile',
    group: 'D',
    confederation: 'CONMEBOL',
    fifaRanking: 43,
    elo: 1720,
    recentForm: 'DLWWD',
    recentGF: 1.3,
    recentGC: 1.2,
    offenseRating: 71,
    defenseRating: 70,
    formRating: 63,
    overallPower: 69,
  },
  {
    id: 'MLI',
    name: 'Malí',
    group: 'D',
    confederation: 'CAF',
    fifaRanking: 44,
    elo: 1680,
    recentForm: 'WDDWL',
    recentGF: 1.2,
    recentGC: 1.0,
    offenseRating: 68,
    defenseRating: 71,
    formRating: 65,
    overallPower: 68,
  },
  {
    id: 'UZB',
    name: 'Uzbekistán',
    group: 'D',
    confederation: 'AFC',
    fifaRanking: 68,
    elo: 1560,
    recentForm: 'WDLDD',
    recentGF: 1.0,
    recentGC: 1.2,
    offenseRating: 61,
    defenseRating: 63,
    formRating: 55,
    overallPower: 59,
  },

  // --- GRUPO E ---
  {
    id: 'BRA',
    name: 'Brasil',
    group: 'E',
    confederation: 'CONMEBOL',
    fifaRanking: 5,
    elo: 2020,
    recentForm: 'WDWWW',
    recentGF: 2.1,
    recentGC: 0.8,
    offenseRating: 93,
    defenseRating: 87,
    formRating: 85,
    overallPower: 92,
  },
  {
    id: 'DEN',
    name: 'Dinamarca',
    group: 'E',
    confederation: 'UEFA',
    fifaRanking: 16,
    elo: 1820,
    recentForm: 'WDWWL',
    recentGF: 1.7,
    recentGC: 1.0,
    offenseRating: 80,
    defenseRating: 78,
    formRating: 74,
    overallPower: 79,
  },
  {
    id: 'NGA',
    name: 'Nigeria',
    group: 'E',
    confederation: 'CAF',
    fifaRanking: 29,
    elo: 1715,
    recentForm: 'DLLWW',
    recentGF: 1.4,
    recentGC: 1.3,
    offenseRating: 75,
    defenseRating: 67,
    formRating: 60,
    overallPower: 69,
  },
  {
    id: 'CAN',
    name: 'Canadá',
    group: 'E',
    confederation: 'CONCACAF',
    fifaRanking: 49,
    elo: 1660,
    recentForm: 'LDWWD',
    recentGF: 1.3,
    recentGC: 1.5,
    offenseRating: 70,
    defenseRating: 62,
    formRating: 62,
    overallPower: 65,
  },

  // --- GRUPO F ---
  {
    id: 'ESP',
    name: 'España',
    group: 'F',
    confederation: 'UEFA',
    fifaRanking: 3,
    elo: 2085,
    recentForm: 'WWWWW',
    recentGF: 2.6,
    recentGC: 0.6,
    offenseRating: 97,
    defenseRating: 91,
    formRating: 98,
    overallPower: 95,
  },
  {
    id: 'TUN',
    name: 'Túnez',
    group: 'F',
    confederation: 'CAF',
    fifaRanking: 41,
    elo: 1630,
    recentForm: 'DDWLD',
    recentGF: 1.0,
    recentGC: 1.1,
    offenseRating: 63,
    defenseRating: 69,
    formRating: 54,
    overallPower: 64,
  },
  {
    id: 'AUS',
    name: 'Australia',
    group: 'F',
    confederation: 'AFC',
    fifaRanking: 24,
    elo: 1740,
    recentForm: 'WWLDW',
    recentGF: 1.5,
    recentGC: 1.0,
    offenseRating: 73,
    defenseRating: 74,
    formRating: 72,
    overallPower: 73,
  },
  {
    id: 'CRC',
    name: 'Costa Rica',
    group: 'F',
    confederation: 'CONCACAF',
    fifaRanking: 54,
    elo: 1575,
    recentForm: 'DLDWW',
    recentGF: 1.2,
    recentGC: 1.5,
    offenseRating: 65,
    defenseRating: 60,
    formRating: 60,
    overallPower: 61,
  },

  // --- GRUPO G ---
  {
    id: 'USA',
    name: 'Estados Unidos',
    group: 'G',
    confederation: 'CONCACAF',
    fifaRanking: 12,
    elo: 1810,
    recentForm: 'WLDWW',
    recentGF: 1.9,
    recentGC: 1.1,
    offenseRating: 81,
    defenseRating: 76,
    formRating: 75,
    overallPower: 79,
  },
  {
    id: 'UKR',
    name: 'Ucrania',
    group: 'G',
    confederation: 'UEFA',
    fifaRanking: 25,
    elo: 1790,
    recentForm: 'WDWDW',
    recentGF: 1.6,
    recentGC: 1.1,
    offenseRating: 78,
    defenseRating: 75,
    formRating: 76,
    overallPower: 77,
  },
  {
    id: 'SEN',
    name: 'Senegal',
    group: 'G',
    confederation: 'CAF',
    fifaRanking: 17,
    elo: 1800,
    recentForm: 'WDWLW',
    recentGF: 1.5,
    recentGC: 0.9,
    offenseRating: 76,
    defenseRating: 81,
    formRating: 73,
    overallPower: 78,
  },
  {
    id: 'IRQ',
    name: 'Irak',
    group: 'G',
    confederation: 'AFC',
    fifaRanking: 58,
    elo: 1550,
    recentForm: 'WLDLL',
    recentGF: 1.1,
    recentGC: 1.6,
    offenseRating: 60,
    defenseRating: 55,
    formRating: 48,
    overallPower: 54,
  },

  // --- GRUPO H ---
  {
    id: 'POR',
    name: 'Portugal',
    group: 'H',
    confederation: 'UEFA',
    fifaRanking: 7,
    elo: 1990,
    recentForm: 'WWLWW',
    recentGF: 2.4,
    recentGC: 0.8,
    offenseRating: 92,
    defenseRating: 86,
    formRating: 85,
    overallPower: 90,
  },
  {
    id: 'COL',
    name: 'Colombia',
    group: 'H',
    confederation: 'CONMEBOL',
    fifaRanking: 14,
    elo: 1910,
    recentForm: 'WWDWW',
    recentGF: 1.8,
    recentGC: 0.9,
    offenseRating: 82,
    defenseRating: 83,
    formRating: 85,
    overallPower: 86,
  },
  {
    id: 'ALG',
    name: 'Argelia',
    group: 'H',
    confederation: 'CAF',
    fifaRanking: 39,
    elo: 1670,
    recentForm: 'DDWLD',
    recentGF: 1.2,
    recentGC: 1.2,
    offenseRating: 69,
    defenseRating: 67,
    formRating: 58,
    overallPower: 66,
  },
  {
    id: 'HON',
    name: 'Honduras',
    group: 'H',
    confederation: 'CONCACAF',
    fifaRanking: 78,
    elo: 1480,
    recentForm: 'LDLLD',
    recentGF: 0.8,
    recentGC: 1.9,
    offenseRating: 50,
    defenseRating: 51,
    formRating: 42,
    overallPower: 47,
  },

  // --- GRUPO I ---
  {
    id: 'ITA',
    name: 'Italia',
    group: 'I',
    confederation: 'UEFA',
    fifaRanking: 9,
    elo: 1920,
    recentForm: 'WDWDW',
    recentGF: 1.6,
    recentGC: 0.8,
    offenseRating: 83,
    defenseRating: 87,
    formRating: 78,
    overallPower: 85,
  },
  {
    id: 'PER',
    name: 'Perú',
    group: 'I',
    confederation: 'CONMEBOL',
    fifaRanking: 32,
    elo: 1710,
    recentForm: 'DLWDL',
    recentGF: 1.1,
    recentGC: 1.2,
    offenseRating: 68,
    defenseRating: 73,
    formRating: 55,
    overallPower: 67,
  },
  {
    id: 'JPN',
    name: 'Japón',
    group: 'I',
    confederation: 'AFC',
    fifaRanking: 18,
    elo: 1860,
    recentForm: 'WWWWD',
    recentGF: 2.2,
    recentGC: 1.0,
    offenseRating: 88,
    defenseRating: 78,
    formRating: 90,
    overallPower: 85,
  },
  {
    id: 'CIV',
    name: 'Costa de Marfil',
    group: 'I',
    confederation: 'CAF',
    fifaRanking: 38,
    elo: 1705,
    recentForm: 'WWWLD',
    recentGF: 1.5,
    recentGC: 1.1,
    offenseRating: 74,
    defenseRating: 72,
    formRating: 72,
    overallPower: 72,
  },

  // --- GRUPO J ---
  {
    id: 'GER',
    name: 'Alemania',
    group: 'J',
    confederation: 'UEFA',
    fifaRanking: 11,
    elo: 1940,
    recentForm: 'WWDWW',
    recentGF: 2.2,
    recentGC: 1.1,
    offenseRating: 89,
    defenseRating: 82,
    formRating: 82,
    overallPower: 87,
  },
  {
    id: 'URU',
    name: 'Uruguay',
    group: 'J',
    confederation: 'CONMEBOL',
    fifaRanking: 11,
    elo: 1930,
    recentForm: 'WWDLW',
    recentGF: 1.8,
    recentGC: 1.0,
    offenseRating: 84,
    defenseRating: 83,
    formRating: 78,
    overallPower: 85,
  },
  {
    id: 'MAR',
    name: 'Marruecos',
    group: 'J',
    confederation: 'CAF',
    fifaRanking: 13,
    elo: 1850,
    recentForm: 'WDWLW',
    recentGF: 1.6,
    recentGC: 0.9,
    offenseRating: 80,
    defenseRating: 84,
    formRating: 75,
    overallPower: 81,
  },
  {
    id: 'QAT',
    name: 'Catar',
    group: 'J',
    confederation: 'AFC',
    fifaRanking: 46,
    elo: 1570,
    recentForm: 'WWLLD',
    recentGF: 1.2,
    recentGC: 1.6,
    offenseRating: 65,
    defenseRating: 58,
    formRating: 58,
    overallPower: 60,
  },

  // --- GRUPO K ---
  {
    id: 'NED',
    name: 'Países Bajos',
    group: 'K',
    confederation: 'UEFA',
    fifaRanking: 8,
    elo: 1950,
    recentForm: 'WWLDW',
    recentGF: 2.0,
    recentGC: 1.1,
    offenseRating: 87,
    defenseRating: 83,
    formRating: 76,
    overallPower: 85,
  },
  {
    id: 'CRO',
    name: 'Croacia',
    group: 'K',
    confederation: 'UEFA',
    fifaRanking: 10,
    elo: 1880,
    recentForm: 'WLDWD',
    recentGF: 1.5,
    recentGC: 1.2,
    offenseRating: 78,
    defenseRating: 80,
    formRating: 68,
    overallPower: 79,
  },
  {
    id: 'TUR',
    name: 'Turquía',
    group: 'K',
    confederation: 'UEFA',
    fifaRanking: 27,
    elo: 1750,
    recentForm: 'WWLDD',
    recentGF: 1.6,
    recentGC: 1.3,
    offenseRating: 78,
    defenseRating: 70,
    formRating: 70,
    overallPower: 74,
  },
  {
    id: 'PAN',
    name: 'Panamá',
    group: 'K',
    confederation: 'CONCACAF',
    fifaRanking: 37,
    elo: 1615,
    recentForm: 'DLDWW',
    recentGF: 1.2,
    recentGC: 1.4,
    offenseRating: 66,
    defenseRating: 62,
    formRating: 65,
    overallPower: 64,
  },

  // --- GRUPO L ---
  {
    id: 'BEL',
    name: 'Bélgica',
    group: 'L',
    confederation: 'UEFA',
    fifaRanking: 6,
    elo: 1960,
    recentForm: 'DWDWW',
    recentGF: 2.1,
    recentGC: 1.0,
    offenseRating: 86,
    defenseRating: 81,
    formRating: 78,
    overallPower: 84,
  },
  {
    id: 'SUI',
    name: 'Suiza',
    group: 'L',
    confederation: 'UEFA',
    fifaRanking: 19,
    elo: 1815,
    recentForm: 'WDDWD',
    recentGF: 1.4,
    recentGC: 1.1,
    offenseRating: 75,
    defenseRating: 79,
    formRating: 72,
    overallPower: 77,
  },
  {
    id: 'RSA',
    name: 'Sudáfrica',
    group: 'L',
    confederation: 'CAF',
    fifaRanking: 60,
    elo: 1565,
    recentForm: 'WWLDD',
    recentGF: 1.2,
    recentGC: 1.3,
    offenseRating: 66,
    defenseRating: 65,
    formRating: 64,
    overallPower: 64,
  },
  {
    id: 'IRN',
    name: 'Irán',
    group: 'L',
    confederation: 'AFC',
    fifaRanking: 20,
    elo: 1725,
    recentForm: 'WDWDW',
    recentGF: 1.6,
    recentGC: 1.0,
    offenseRating: 76,
    defenseRating: 72,
    formRating: 75,
    overallPower: 74,
  }
];

export const PARAMS_INITIAL: SimulatorParams = {
  version: '1.2.0',
  updateDate: '2026-06-01',
  mode: 'auto',
  weightFifa: 20,
  weightElo: 30,
  weightOffense: 20,
  weightDefense: 15,
  weightForm: 15,
  tieBreakCriteria: 'pts_dg_gf_head',
  extraTimeRules: 'et_then_penalties',
};
